abstract: Catalyst plugin for lighttpd's X-Sendfile.
author: Daisuke Murase <typester@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-Plugin-XSendFile
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.6902
  Catalyst::Utils: 0
  Class::Data::Inheritable: 0
  File::Temp: 0
  File::stat: 0
  NEXT: 0
  Path::Class: 0
  Scalar::Util: 0
  bytes: 0
version: 0.03_001
