---
name: Catalyst-Plugin-XSendFile
version: 0.02
author:
  - 'Daisuke Murase <typester@cpan.org>'
abstract: Catalyst plugin for lighttpd's X-Sendfile.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.6902
  Class::Data::Inheritable: 0
  MIME::Types: 0
  NEXT: 0
  Path::Class: 0
provides:
  Catalyst::Plugin::XSendFile:
    file: lib/Catalyst/Plugin/XSendFile.pm
    version: 0.02
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
